apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: invoce-extractor
  description: AI-assisted PDF/Image receipt extractor tool
  annotations:
    github.com/project-slug: EnzoReyes11/invoce-extractor
    backstage.io/techdocs-ref: dir:.
    scaffolder.backstage.io/template: bare-minimum@1.0.0
spec:
  type: service
  lifecycle: experimental
  owner: group:default/internal
