name: Worklog

on:
  push:
    branches: [main]

jobs:
  worklog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: EnzoReyes11/worklog-action@v1
        with:
          github-token: ${{ '${{' }} secrets.GITHUB_TOKEN ${{ '}}' }}
